/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;
import Model.Connection;
import Model.Penulis;
import java.sql.PreparedStatement;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harke
 */
public class FPenulis extends javax.swing.JFrame {
    
    List<Penulis> items = new ArrayList<>();
    
    /**
     * Creates new form Penulis
     */
    public FPenulis() {
        initComponents();
    }
    
    public void showTableData()
    {
        Connection.koneksi();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama Penulis");
        String sql = "SELECT * FROM penulis";
        try {
            items.clear();
           Connection.rs = Connection.stmt.executeQuery(sql); 
           while(Connection.rs.next())
           {
               items.add(new Penulis(Connection.rs.getInt("id"), Connection.rs.getString("nama")));
           }
           
           int i = 1;
           for(Penulis p: items)
           {
               model.addRow(new Object[] {
                   i,p.getNama()
               });
               i++;
           }
           Connection.rs.close();
           tblPenulis.setModel(model);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPenulis = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenulis = new javax.swing.JTable();
        tblUbah = new javax.swing.JButton();
        tblHapus = new javax.swing.JButton();
        btnKosong = new javax.swing.JButton();
        txtID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Master Penulis");

        jLabel2.setText("Nama Penulis");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblPenulis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPenulis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenulisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPenulis);

        tblUbah.setText("Ubah");
        tblUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblUbahActionPerformed(evt);
            }
        });

        tblHapus.setText("Hapus");
        tblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHapusActionPerformed(evt);
            }
        });

        btnKosong.setText("Kosongkan");
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tblUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tblHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKosong))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(txtPenulis)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(tblUbah)
                    .addComponent(tblHapus)
                    .addComponent(btnKosong))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String nama = txtPenulis.getText();
        String sql = "INSERT INTO penulis (nama) VALUES (?)";
        try {
            PreparedStatement pms = Connection.conn.prepareStatement(sql);
            pms.setString(1, nama);
            pms.execute();
            Connection.stmt.close();
            Connection.conn.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        showTableData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblPenulisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenulisMouseClicked
        // TODO add your handling code here:
        int baris = tblPenulis.getSelectedRow();
        txtPenulis.setText(items.get(baris).getNama());
        txtID.setVisible(false);
        txtID.setText(Integer.toString(items.get(baris).getId()));
        tblUbah.setEnabled(true);
        tblHapus.setEnabled(true);
    }//GEN-LAST:event_tblPenulisMouseClicked

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        // TODO add your handling code here:
        txtPenulis.setText("");
    }//GEN-LAST:event_btnKosongActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        showTableData();
        tblUbah.setEnabled(false);
        tblHapus.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void tblUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblUbahActionPerformed
        // TODO add your handling code here:
        String nama = txtPenulis.getText();
        int id = Integer.parseInt(txtID.getText());
        String sql = "UPDATE penulis SET nama=? WHERE id=?";
        try{
            PreparedStatement pms = Connection.conn.prepareStatement(sql);
            pms.setString(1, nama);
            pms.setInt(2, id);
            pms.execute();
            Connection.stmt.close();
            Connection.conn.close();
        }
        catch(Exception e)
        {
             e.printStackTrace();
        }
        
        showTableData();
    }//GEN-LAST:event_tblUbahActionPerformed

    private void tblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHapusActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtID.getText());
        String sql = "DELETE FROM penulis WHERE id=?";
        try{
            PreparedStatement pms = Connection.conn.prepareStatement(sql);
            pms.setInt(1, id);
            pms.execute();
            Connection.stmt.close();
            Connection.conn.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        showTableData();
    }//GEN-LAST:event_tblHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKosong;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tblHapus;
    private javax.swing.JTable tblPenulis;
    private javax.swing.JButton tblUbah;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtPenulis;
    // End of variables declaration//GEN-END:variables
}
